FROM python:3.8.4-alpine3.12

RUN apk add --update \
    curl bash gcc musl-dev \
    openssl-dev libffi-dev rust cargo \
    && rm -rf /var/cache/apk/*;

COPY . .

RUN chmod +x fetch_dependencies.sh

RUN sh ./fetch_dependencies.sh

RUN chmod +x run_tests.sh

ENTRYPOINT ["./run_tests.sh"]